### ISSUE TITLE
Eq and Show instances

### ISSUE THREAD

**Issue by andrewthad** [haskell-streaming/streaming#3]
[Original issue](https://github.com/michaelt/streaming/issues/26) by @andrewthad. There is a bit of discussion there.

**Comment by treeowl** [comment]
I've assigned myself for now, but anyone else is free to work on this. As I stated on the old ticket, I think flexible contexts should probably be preferred to the `...1` classes, so that probably puts me in opposition to @andrewthad. Surely we agree that `==` should call `unexposed`. There are a number of missing instances of classes in `Data.Functor.Classes`, both for `Of` and for `Stream`. These are a bit of a pain to write by hand, but deriving them requires TH and another dependency. Ugh.

**Comment by andrewthad** [comment]
Let's stay with the flexible contexts approach for now. we should definitely fix them so that == (And compare for that matter) calls unexposed. I have a branch I was working on where I have Eq1 and friends implemented. The worst part is, since we provide compatibility back to transformers 0.4, I had to use CPP to make it build, since the type classes were defined differently back then.

If anyone (probably Ryan Scott) ever writes a GHC extension for deriving the higher kinded type classes, I think at that point it would be worthwhile to switch over to using them in the contexts of the regular ones.

**Comment by andrewthad** [comment]
I'm in agreement with that, although I don't think I communicated it well. I was just trying to say that I mostly already have them written (with backwards compatibility for transformers)

**Comment by treeowl** [comment]
I don't think there's much point providing compatibility with ancient `transformers`. Does anyone really care? My current PR just drops that. If you think people really rely on being able to use old `transformers` versions with new `streaming` versions, I guess I can put in CPP.

**Comment by andrewthad** [comment]
Now that I think about it, I don't actually care about supporting `transformers` < 0.5. I had only done that originally because I saw that `streaming`'s lower bound for `transformers` was 0.4, but I kind of forgot that we can just change that.
