### ISSUE TITLE
Cut a new release of streaming-utils

### ISSUE THREAD

**Issue by ocharles** [haskell-streaming/streaming#34]
I just transferred streaming-utils to haskell-streaming ([here](https://github.com/haskell-streaming/streaming-utils)), but it doesn't have issues enabled. I also don't have admin access to enable issues, so apologies for the odd round-about way of opening an issue here instead.

Anyway, `streaming-utils` on Hackage isn't buildable with the latest versions of dependencies, notably `streaming-0.2`. In `haskell-streaming/streaming-utils` I've fixed that. We just need to get maintainership on Hackage and upload. @andrewthad, would you mind getting that access?

**Comment by treeowl** [comment]
I've enabled issues for that repository.

On Jan 3, 2018 10:00 AM, "Oliver Charles" <notifications@github.com> wrote:

I just transferred streaming-utils to haskell-streaming (here
<https://github.com/haskell-streaming/streaming-utils>), but it doesn't
have issues enabled. I also don't have admin access to enable issues, so
apologies for the odd round-about way of opening an issue here instead.

Anyway, streaming-utils on Hackage isn't buildable with the latest versions
of dependencies, notably streaming-0.2. In haskell-streaming/streaming-utils
I've fixed that. We just need to get maintainership on Hackage and upload.
@andrewthad <https://github.com/andrewthad>, would you mind getting that
access?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell-streaming/streaming/issues/34>, or mute the
thread

**Comment by fosskers** [comment]
A new release of `streaming-utils` would be very helpful.

**Comment by chessai** [comment]
I got that access a few weeks ago and posted it about it at https://github.com/haskell-streaming/streaming-utils/issues/2. If no one uploads streaming-utils by tomorrow morning I can do so.

**Comment by fosskers** [comment]
@chessai I've since cut a release of a stand-alone [`streaming-attoparsec`](https://hackage.haskell.org/package/streaming-attoparsec) (the code of which is ripped straight from this repo), and plan to do `streaming-aeson` in the near future (which this lib also provides).

**Comment by chessai** [comment]
@fosskers thanks for that. would it be considered advantageous to make streaming-utils more modular, ie having `streaming-attoparsec`, `streaming-aeson`, etc. for backward compatibility, streaming-utils could just re-export those things.

**Comment by chessai** [comment]
can't build this with just `cabal` right now. getting a bunch of c linker errors...will investigate later

**Comment by chessai** [comment]
This should be closed, I already did this.

However we should do the thing @fosskers talks about. I'll open a new issue.
