### ISSUE TITLE
enumFrom documentation seems inaccurate

### ISSUE THREAD

**Issue by jchia** [haskell-streaming/streaming#91]
The documentation for `enumFrom` disagrees with my REPL experiment.
https://hackage.haskell.org/package/streaming-0.2.3.0/docs/Streaming-Prelude.html#v:enumFrom

I replaced the `S.enumFrom 1` with `S.each [1..]` and got the same result, contrary to the documentation which says "With each [1..] the following bit of connect-and-resume would be impossible". Is the documentation out of date or am I misreading the documentation?

**Comment by danidiaz** [comment]
You are correct that with `S.each [1..]` it works. What fails is using `S.each ['a'..]`, like this:

    rest <- S.print $ S.zip (S.each ['a'..]) $ S.splitAt 3 $ S.enumFrom 1

The reason is that `S.splitAt` puts "the rest of the stream" in the resulting `Stream`'s return value. Since the stream created by `S.each ['a'...]` has return type `()` instead of being polymorphic, there's now a type mismatch in `S.zip`.

So perhaps the example should be changed to mention `S.each ['a'..]` instead.
